name: Run tests and build the site

on:
  push:

jobs:
  development:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Create env file
        run: |
          touch .env.production
          echo GATSBY_APP_SUPABASE_URL = ${{ secrets.GATSBY_APP_SUPABASE_URL }} >> .env.production
          echo GATSBY_APP_SUPABASE_ANON_KEY = ${{ secrets.GATSBY_APP_SUPABASE_ANON_KEY }} >> .env.production
      - name: Keep yarn cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Compile TypeScript
        run: yarn tsc
      - name: Run Unit Tests
        run: yarn test
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: conference-buddy-web-app-${{ github.sha }}
          path: public
