name: Run tests and build the site

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Keep yarn cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Compile TypeScript
        run: npx tsc
      - name: Run Unit Tests
        run: yarn test
      - name: Build
        run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: conference-buddy-web-app-${{ github.sha }}
          path: public
